### ISSUE TITLE
Rails deprecating old enum syntax

### ISSUE THREAD

**Issue by cswilliams** [betacraft/rich_enums#6]
We just upgraded our app to Rails 7.2 and now everywhere we're using `rich_enums` is generating the following deprecation warning in our logs: 
```
DEPRECATION WARNING: Defining enums with keyword arguments is deprecated and will be removed
in Rails 8.0. Positional arguments should be used instead
```

Just curious if there is a way to fix this or if we'll need to wait for an update to the gem?

Thanks

**Comment by harunkumars** [comment]
Thanks for the report. This has been addressed in [v0.1.5](https://github.com/betacraft/rich_enums/releases/tag/v0.1.5)
